{
 "title": "Jenkins exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_jobs_total" }
   ]
  },
  {
   "title": "In Queue Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_queue_total" }
   ]
  },
  {
   "title": "Total Node",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_nodes_total" }
   ]
  },
  {
   "title": "Total Online Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_nodes_online_total" }
   ]
  },
  {
   "title": "Building Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_jobs_building_total{job=\"Devops-exporter\"}"
    }
   ]
  },
  {
   "title": "Total Offline Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_nodes_offline_total" }
   ]
  },
  {
   "title": "Job fail 10+ times",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(jenkins_job_fail_consecutively >= 10)",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Job fail 50+ times",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(jenkins_job_fail_consecutively >= 50)",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Total Executor",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_executors_total" }
   ]
  },
  {
   "title": "Executor Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_executors_free" }
   ]
  },
  {
   "title": "Job fail 100+ times",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(jenkins_job_fail_consecutively >= 100)",
     "legendFormat": "{{jobname}}"
    }
   ]
  },
  {
   "title": "Executor Busy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_executors_busy" }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_jobs_total", "legendFormat": "Total Jobs" }
   ]
  },
  {
   "title": "In Queue Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_total", "legendFormat": "Job in queue" }
   ]
  },
  {
   "title": "Building Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_jobs_building_total", "legendFormat": "Building Jobs" }
   ]
  },
  {
   "title": "In Queue Jobs",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_queue_total" }
   ]
  },
  {
   "title": "List jobs in Queue",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 2, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(jenkins_queue_item_duration)",
     "legendFormat": "{{item_name}} - {{queue_id}} "
    }
   ]
  },
  {
   "title": "Building Jobs",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 2, "x": 11, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_jobs_building_total{job=\"Devops-exporter\"}"
    }
   ]
  },
  {
   "title": "List jobs Building",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(jenkins_jobs_building_time_seconds{status='building'})",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job fail 10+ times",
   "type": "graph",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jenkins_job_fail_consecutively >= 10)",
     "legendFormat": "Jobs fail 10+ times"
    },
    {
     "expr": "count(jenkins_job_fail_consecutively >= 50)",
     "legendFormat": "Jobs fail 50+ times"
    },
    {
     "expr": "count(jenkins_job_fail_consecutively >= 100)",
     "legendFormat": "Jobs fail 100+ times"
    }
   ]
  },
  {
   "title": "Job fail 10+ times",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "jenkins_job_fail_consecutively >= 10",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Total Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Nodes" }
   ],
   "targets": [
    { "expr": "jenkins_nodes_total", "legendFormat": "Total" },
    { "expr": "jenkins_nodes_online_total", "legendFormat": "On" },
    { "expr": "jenkins_nodes_offline_total", "legendFormat": "Off" }
   ]
  },
  { "title": "Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Total Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executors_total", "legendFormat": "Total" },
    { "expr": "jenkins_executors_free", "legendFormat": "Free" },
    { "expr": "jenkins_executors_busy", "legendFormat": "Busy" }
   ]
  },
  {
   "title": "Master Available Physical Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "(100 * jenkins_node_available_physical_memory{node_type = 'master', node=\"(master)\"}) / jenkins_node_total_physical_memory{node_type = 'master', node=\"(master)\"}"
    }
   ]
  },
  {
   "title": "Master Available Physical Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jenkins_node_available_physical_memory{node_type = 'master', node=\"(master)\"}",
     "legendFormat": "Available Physical Memory"
    },
    {
     "expr": "jenkins_node_available_swap_space{node_type = 'master', node = '(master)'}",
     "legendFormat": "Available Swap Space"
    }
   ]
  },
  {
   "title": "Master Available Swap Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "(100 * jenkins_node_available_swap_space{node_type = 'master', node='(master)'}) / jenkins_node_total_swap_space{node_type = 'master', node='(master)'}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } }
 ]
}