{
 "title": "Sonar Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_total" }
   ]
  },
  {
   "title": "Total Projects Passed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_ok" }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "singlestat",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_total" }
   ]
  },
  {
   "title": "Total Tasks Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_success" }
   ]
  },
  {
   "title": "Total Profiles",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_profiles_total " }
   ]
  },
  {
   "title": "Total Users",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_users_total" }
   ]
  },
  {
   "title": "Total Projects Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_error" }
   ]
  },
  {
   "title": "Total Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_failed" }
   ]
  },
  {
   "title": "Total Projects Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_warn" }
   ]
  },
  {
   "title": "Total Tasks Canceler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_canceled" }
   ]
  },
  {
   "title": "Total Languages",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_languages_total" }
   ]
  },
  {
   "title": "Total Groups",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_groups_total" }
   ]
  },
  {
   "title": "Total Projects not analyzed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_none" }
   ]
  },
  {
   "title": "Total Tasks Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_pending" }
   ]
  },
  {
   "title": "Total Projects deny access",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_projects_access_denied" }
   ]
  },
  {
   "title": "Total Tasks in Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_tasks_in_progress" }
   ]
  },
  { "title": "Project info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sonar_projects_total", "legendFormat": "Total" },
    { "expr": "sonar_projects_ok", "legendFormat": "Passed" },
    { "expr": "sonar_projects_error", "legendFormat": "Failed" },
    { "expr": "sonar_projects_none", "legendFormat": "None" },
    { "expr": "sonar_projects_warn", "legendFormat": "Warning" },
    { "expr": "sonar_projects_access_denied", "legendFormat": "N/A" }
   ]
  },
  { "title": "Task info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pending and In Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sonar_tasks_pending", "legendFormat": "Pending" },
    { "expr": "sonar_tasks_in_progress", "legendFormat": "In progress" }
   ]
  },
  {
   "title": "Tasks Pending",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sonar_task_execution_time_second{task_status='PENDING'}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Tasks in Progress",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "sonar_task_execution_time_second{task_status='IN_PROGRESS'}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  { "title": "Profile info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Profiles",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_profiles_total " }
   ]
  },
  {
   "title": "Number Profiles of Language",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sonar_language_profiles_total{})",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Total Languages",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_languages_total" }
   ]
  },
  { "title": "User info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 48 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_users_total" }
   ]
  },
  {
   "title": "Total User in each Group",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 48 },
   "targets": [
    { "expr": "sonar_group_users_total", "legendFormat": "{{gr_name}}" }
   ]
  },
  {
   "title": "Total Groups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 53 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_groups_total" }
   ]
  },
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Web JVM State Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 59 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_system_web_memory_max{}" }
   ]
  },
  {
   "title": "Web JVM State Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 59 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_system_web_memory_free{}" }
   ]
  },
  {
   "title": "Web JVM State Threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 59 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_system_web_threads{}" }
   ]
  },
  {
   "title": "Search Engine Disk Available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sonar_system_search_disk_available{}"
    }
   ]
  },
  {
   "title": "Web JVM State Threads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 59 },
   "targets": [
    { "expr": "sonar_system_web_threads{}" }
   ]
  },
  {
   "title": "Compute JVM State Threads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 59 },
   "targets": [
    { "expr": "sonar_system_compute_threads{}" }
   ]
  },
  {
   "title": "Compute JVM State Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 64 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_system_compute_memory_max{}"
    }
   ]
  },
  {
   "title": "Compute JVM State Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 64 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_system_compute_memory_free{}"
    }
   ]
  },
  {
   "title": "Compute JVM State Threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sonar_system_compute_threads{}" }
   ]
  },
  {
   "title": "Search Engine Max File Descriptors",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_system_search_file_desc_max{} - sonar_system_search_file_desc_open{}",
     "legendFormat": "Free"
    },
    {
     "expr": "sonar_system_search_file_desc_open{}",
     "legendFormat": "Open File Descriptors"
    }
   ]
  },
  {
   "title": "Search Engine Disk Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 69 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_system_search_disk_available{}"
    }
   ]
  },
  {
   "title": "Search Engine Max File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 69 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_system_search_file_desc_max{}"
    }
   ]
  },
  {
   "title": "Search Engine Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 69 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_system_search_file_desc_open{}"
    }
   ]
  },
  {
   "title": "Web JVM State Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sonar_system_web_memory_max{}", "legendFormat": "Max" },
    {
     "expr": "sonar_system_web_memory_max{} - sonar_system_web_memory_free{}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Compute Engine JVM State Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sonar_system_compute_memory_max{}",
     "legendFormat": "Max"
    },
    {
     "expr": "sonar_system_compute_memory_max{}-sonar_system_compute_memory_free{}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}